[package]
name = "perm"
version = "0.4.0"
authors = ["pgecsenyi <pgecsenyi@protonmail.com>"]
edition = "2018"

[dependencies]
csv = "1.0.5"
serde = "1.0.86"
serde_json = "1.0.38"
serde_derive = "1.0.68"
structopt = "0.2.15"
time = "0.1.42"
